name: Publish Pages

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Create javadoc with Gradle Wrapper
        run: ./gradlew javadoc
      - name: Create Site Artifact
        run: |
          mkdir site
          mv build/docs/javadoc site/
      - name: Upload Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
  pages:
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
